version: '3'

services:
  app:
    env_file: .env
    container_name: app
    ports:
      - "${PORT}:${PORT}"
    image: tp-tap
    build: .
    depends_on:
      - db
    volumes:
      - ./image:/home/node/app/image
    environment:
      - DB_URL=mongodb://db:27017/

  db:
    container_name: db
    image: mongo:5.0.3-focal
    volumes:
      - ./data:/data/db

networks:
  app-net:
